# Generated by Django 6.0.3 on 2026-04-05 18:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voucher Usage',
                'verbose_name_plural': 'Voucher Usages',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_item', 'Free Item'), ('bundle', 'Bundle Deal')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order amount to qualify for this offer', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('hero_title', models.CharField(blank=True, max_length=100)),
                ('hero_subtitle', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(blank=True, upload_to='offers/hero/')),
                ('display_on_hero', models.BooleanField(default=False, help_text='Show this offer on the homepage hero banner')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_usage_count', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all categories', related_name='applicable_offers', to='menu.menucategory')),
                ('applicable_items', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all items', related_name='applicable_offers', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited uses')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1, help_text='0 = unlimited per customer')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_codes', to='offers.offer')),
            ],
            options={
                'verbose_name': 'Voucher Code',
                'verbose_name_plural': 'Voucher Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
