# Generated by Django 6.0.3 on 2026-04-09 09:06

import apps.core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='offers/hero/', validators=[apps.core.media.ProductionImageValidator(max_bytes=5242880)]),
        ),
    ]
