# Generated by Django 6.0.3 on 2026-06-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='app_exclusive',
            field=models.BooleanField(default=False, help_text='Show this as a signed-in app/account reward.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='audience',
            field=models.CharField(choices=[('all', 'All Customers'), ('first_order', 'First Order'), ('birthday', 'Birthday'), ('off_peak', 'Off-Peak')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='badge',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='offer',
            name='off_peak_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='off_peak_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
