# Generated by Django 6.0.3 on 2026-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_ready_time',
            field=models.DateTimeField(blank=True, help_text='When order was actually marked ready', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, help_text="Kitchen's estimated ready time", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_pickup_time',
            field=models.DateTimeField(blank=True, help_text="Customer's requested pickup time", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal kitchen notes'),
        ),
    ]
