# Generated by Django 6.0.3 on 2026-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_pickup_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], db_index=True, default='pickup', max_length=20),
        ),
    ]
