# Generated by Django 6.0.3 on 2026-06-02 09:08

import apps.orders.models
import django.core.validators
from django.db import migrations, models


def backfill_preparation_time_minutes(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    default_prep_time = 15

    for item in OrderItem.objects.select_related("menu_item").iterator():
        prep_time = default_prep_time
        if item.menu_item_id and item.menu_item.preparation_time:
            prep_time = item.menu_item.preparation_time
        OrderItem.objects.filter(pk=item.pk).update(
            preparation_time_minutes=max(1, int(prep_time))
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_backfill_delivery_dispatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=apps.orders.models.default_preparation_time_minutes, help_text="Snapshot of this item's prep time when the order was placed.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(backfill_preparation_time_minutes, noop_reverse),
    ]
