# Generated by Django 6.0.3 on 2026-06-03 19:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_distance_miles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_distance_miles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('max_distance_miles', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_distance_miles', 'max_distance_miles'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilment_slot_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverydriver'),
        ),
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('planned_departure_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='orders.deliverydriver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfilmentBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('all', 'All'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], db_index=True, default='all', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['service_type', 'starts_at', 'ends_at', 'is_active'], name='orders_fulf_service_ccc590_idx')],
            },
        ),
        migrations.CreateModel(
            name='FulfilmentCapacityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], db_index=True, max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 6=Sunday.', validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5)])),
                ('lead_time_minutes', models.PositiveIntegerField(default=15)),
                ('last_order_minutes_before_close', models.PositiveIntegerField(default=15)),
                ('max_orders', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['service_type', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['service_type', 'day_of_week', 'is_active'], name='orders_fulf_service_ec960b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRunOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('eta_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_run_order', to='orders.order')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_orders', to='orders.deliveryrun')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('run', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='FulfilmentSlotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], db_index=True, max_length=20)),
                ('slot_start', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('released', 'Released')], db_index=True, default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservation', to='orders.order')),
            ],
            options={
                'ordering': ['slot_start'],
                'indexes': [models.Index(fields=['service_type', 'slot_start', 'status'], name='orders_fulf_service_168f38_idx')],
            },
        ),
    ]
