# Generated by Django 6.0.6 on 2026-07-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_personal_data_anonymised_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mollie_payment_id',
        ),
    ]
