# Generated by Django 6.0.6 on 2026-07-23 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cancel_surplus_runs(apps, schema_editor):
    """Keep the newest DRAFT and newest DISPATCHED run per driver; cancel the
    rest so the partial unique constraints can be added safely."""
    DeliveryRun = apps.get_model("orders", "DeliveryRun")
    for status in ("draft", "dispatched"):
        seen_drivers = set()
        runs = (
            DeliveryRun.objects.filter(status=status, driver__isnull=False)
            .order_by("driver_id", "-created_at")
        )
        for run in runs:
            if run.driver_id in seen_drivers:
                run.status = "cancelled"
                run.save(update_fields=["status"])
            else:
                seen_drivers.add(run.driver_id)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_mollie_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cancel_surplus_runs, migrations.RunPython.noop),
        migrations.AddField(
            model_name='deliverydriver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='deliveryrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('driver',), name='uniq_draft_run_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='deliveryrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'dispatched')), fields=('driver',), name='uniq_dispatched_run_per_driver'),
        ),
    ]
