# Generated by Django 6.0.3 on 2026-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_zimbabwean_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['nuts', 'dairy', 'gluten', 'shellfish']"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='kcal', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock below this'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='salt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock level'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Enable stock tracking for this item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['vegetarian', 'gluten-free', 'spicy', 'halal', 'vegan']"),
        ),
    ]
