# Generated by Django 6.0.3 on 2026-04-09 09:06

import apps.core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_allergens_menuitem_calories_menuitem_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu/categories/', validators=[apps.core.media.ProductionImageValidator(max_bytes=5242880)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu/items/', validators=[apps.core.media.ProductionImageValidator(max_bytes=5242880)]),
        ),
    ]
