# Generated by Django 6.0.3 on 2026-06-02 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menucategory_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Estimated kitchen prep time in minutes. Used to calculate order ready times.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
