# Generated by Django 6.0.3 on 2026-06-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_preparation_time'),
        ('orders', '0010_deliverydriver_deliveryzone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('adjustment', 'Adjustment'), ('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='menu.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['menu_item', 'created_at'], name='menu_stockm_menu_it_dd13c5_idx'), models.Index(fields=['movement_type', 'created_at'], name='menu_stockm_movemen_a80446_idx')],
            },
        ),
    ]
