# Generated by Django 6.0.6 on 2026-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Audit metadata for imported menu imagery, such as Pixabay id, query, and source page.'),
        ),
    ]
