# Generated by Django 6.0.3 on 2026-06-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerdatarequest'),
        ('menu', '0006_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=160)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('last_added_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_meal_snapshots', to='menu.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_added_at', '-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='accounts_sa_user_id_4b32eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'menu_item', 'item_name'), name='unique_saved_meal_base_item_per_user')],
            },
        ),
    ]
