# Generated by Django 6.0.3 on 2026-06-04 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_loyaltyreward_image'),
        ('offers', '0004_offer_app_exclusive_offer_audience_offer_badge_and_more'),
        ('orders', '0010_deliverydriver_deliveryzone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardWalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('welcome', 'Welcome'), ('birthday', 'Birthday'), ('app_exclusive', 'App Exclusive'), ('off_peak', 'Off-Peak'), ('referral', 'Referral'), ('goodwill', 'Goodwill'), ('admin', 'Admin')], default='app_exclusive', max_length=30)),
                ('points_value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loyalty_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_items', to='loyalty.loyaltyreward')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_items', to='offers.offer')),
                ('used_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_wallet_items', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_wallet_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'expires_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='loyalty_rew_user_id_ce356c_idx'), models.Index(fields=['source', 'created_at'], name='loyalty_rew_source_40dd12_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'offer', 'source'), name='unique_reward_wallet_offer_source_per_user')],
            },
        ),
    ]
