# Generated by Django 6.0.6 on 2026-07-18 18:25

from django.conf import settings
from django.db import migrations, models


def _remove_duplicate_earned_transactions(apps, schema_editor):
    """Keep only the earliest EARNED transaction per (user, order) pair."""
    LoyaltyTransaction = apps.get_model("loyalty", "LoyaltyTransaction")
    seen = set()
    duplicates = []
    earned = LoyaltyTransaction.objects.filter(
        transaction_type="earned", order__isnull=False
    ).order_by("created_at", "pk")
    for pk, user_id, order_id in earned.values_list("pk", "user_id", "order_id"):
        key = (user_id, order_id)
        if key in seen:
            duplicates.append(pk)
        else:
            seen.add(key)
    if duplicates:
        LoyaltyTransaction.objects.filter(pk__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_rewardwalletitem'),
        ('orders', '0014_remove_order_mollie_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_remove_duplicate_earned_transactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'earned')), fields=('user', 'order'), name='unique_earned_points_per_order'),
        ),
    ]
