# Generated by Django 6.0.3 on 2026-04-06 06:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('deal_type', models.CharField(choices=[('combo', 'Combo Meal'), ('family', 'Family Deal'), ('lunch', 'Lunch Special'), ('student', 'Student Deal'), ('custom', 'Build Your Own')], default='combo', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='mealdeals/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_per_order', models.PositiveIntegerField(default=5, help_text='Maximum quantity per order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Deal',
                'verbose_name_plural': 'Meal Deals',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Choose 1 Main'", max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mealdeals.mealdeal')),
            ],
            options={
                'verbose_name': 'Meal Deal Item',
                'verbose_name_plural': 'Meal Deal Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MealDealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra cost for this option (0 = included)', max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('deal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mealdeals.mealdealitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_options', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Meal Deal Option',
                'verbose_name_plural': 'Meal Deal Options',
            },
        ),
    ]
