# Generated by Django 6.0.3 on 2026-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='123 High Street, Harare'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shop_name',
            field=models.CharField(default='Tinashe Zimbabwean Kitchen', max_length=100),
        ),
    ]
