# Generated by Django 6.0.3 on 2026-04-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='shop_name',
            field=models.CharField(default='My Restaurant', max_length=100),
        ),
    ]
