# Generated by Django 6.0.3 on 2026-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_color',
            field=models.CharField(default='#FF6B35', help_text='Hex color code for PWA theme', max_length=7),
        ),
    ]
