# Generated by Django 6.0.3 on 2026-04-09 09:06

import apps.core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='site/', validators=[apps.core.media.ProductionImageValidator(max_bytes=262144, max_height=512, max_width=512)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/', validators=[apps.core.media.ProductionImageValidator(max_bytes=1048576, max_height=1600, max_width=1600)]),
        ),
    ]
