# Generated by Django 6.0.3 on 2026-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettings_favicon_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_enabled',
            field=models.BooleanField(default=True, help_text='Allow customers to choose delivery when the DELIVERY_ENABLED environment switch is also on.'),
        ),
    ]
