# Generated by Django 6.0.3 on 2026-06-02 09:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_delivery_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_map_enabled',
            field=models.BooleanField(default=True, help_text='Use Google Maps address search and delivery-zone validation when API keys and shop coordinates are configured.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_radius_miles',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Maximum delivery distance from the shop in miles.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Shop latitude used for delivery maps. Leave blank to use SHOP_LATITUDE from .env.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shop_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Shop longitude used for delivery maps. Leave blank to use SHOP_LONGITUDE from .env.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
    ]
