# Generated by Django 6.0.3 on 2026-06-03 17:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_delivery_map_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_minimum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('15.00'), help_text='Minimum food subtotal for delivery orders. Leave blank to use DELIVERY_MINIMUM_ORDER_AMOUNT from .env. Use 0 to disable.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
