# Generated by Django 6.0.3 on 2026-06-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_delivery_minimum_order_amount'),
        ('orders', '0010_deliverydriver_deliveryzone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push'), ('email', 'Email')], db_index=True, max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='orders.order')),
            ],
            options={
                'ordering': ['next_attempt_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='core_notifi_status_66223f_idx'), models.Index(fields=['event_type', 'created_at'], name='core_notifi_event_t_4b8384_idx')],
            },
        ),
    ]
