# Generated by Django 6.0.6 on 2026-06-04 19:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_order_personal_data_retention_years'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cart_item_quantity_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum quantity a customer can self-serve for one basket item. Leave blank to use MAX_CART_ITEM_QUANTITY from .env.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.CreateModel(
            name='LargeOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('requested_items', models.TextField(help_text='Customer notes about requested food, quantities, budget, or event needs.')),
                ('basket_snapshot', models.JSONField(blank=True, default=dict)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='large_order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_largeo_status_bdc5ee_idx'), models.Index(fields=['event_datetime'], name='core_largeo_event_d_d9c606_idx')],
            },
        ),
    ]
