# Generated by Django 6.0.6 on 2026-06-04 19:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_cart_item_quantity_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_default_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default delivery fee used before a distance zone is matched, or when manual address entry is used. Leave blank to use DELIVERY_DEFAULT_FEE from .env.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
