# Generated by Django 6.0.6 on 2026-07-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_delivery_default_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_enabled',
            field=models.BooleanField(default=True, help_text='Show the marketing hero banner at the top of the homepage.'),
        ),
    ]
