# Generated by Django 6.0.6 on 2026-07-18 21:14

from django.db import migrations, models


def disable_hero(apps, schema_editor):
    # 0013 seeded existing rows with True as a no-op stepping stone; the
    # ordering-first homepage ships with the hero off until a client
    # opts back in via admin.
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.update(homepage_hero_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_homepage_hero_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_eta_text',
            field=models.CharField(blank=True, help_text='Delivery time estimate shown on the homepage, e.g. "40–60 min". Blank hides it.', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_hero_enabled',
            field=models.BooleanField(default=False, help_text='Show the marketing hero banner at the top of the homepage.'),
        ),
        migrations.RunPython(disable_hero, migrations.RunPython.noop),
    ]
