# Generated by Django 6.0.6 on 2026-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_delivery_eta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='refund_policy_text',
            field=models.TextField(blank=True, help_text='Return/refund policy shown on receipts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT registration number shown on receipts', max_length=30),
        ),
    ]
