# Generated by Django 6.0.3 on 2026-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mollie', 'Mollie'), ('demo', 'Demo')], db_index=True, default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mollie_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
