# Generated by Codex on 2026-04-10

from django.db import migrations


def backfill_payment_provider_fields(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    for payment in Payment.objects.all():
        payment.external_payment_id = payment.external_payment_id or payment.mollie_payment_id or ""
        payment.external_payment_method = (
            payment.external_payment_method or payment.mollie_payment_method or ""
        )
        if payment.provider == "stripe":
            payment.provider = "demo" if payment.mollie_payment_id.startswith("demo_") else "mollie"
        payment.save(
            update_fields=[
                "provider",
                "external_payment_id",
                "external_payment_method",
            ]
        )


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_external_payment_id_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_payment_provider_fields, noop),
    ]
