# Generated by Django 6.0.3 on 2026-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_backfill_payment_provider_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mollie', 'Mollie'), ('demo', 'Demo'), ('offline_pending', 'Offline Pending')], db_index=True, default='stripe', max_length=20),
        ),
    ]
