# Generated by Django 6.0.3 on 2026-06-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_expires_at_alter_payment_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card_terminal', 'Card Terminal'), ('phone_card', 'Phone Card')], db_index=True, max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=8)),
                ('change_given', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reference_code', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_receipt', to='payments.payment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Payment Receipt',
                'verbose_name_plural': 'Manual Payment Receipts',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
