# Generated by Django 6.0.6 on 2026-07-18 18:07

from django.db import migrations, models


def _ensure_no_mollie_payments(apps, schema_editor):
    """Safety guard: refuse to drop Mollie columns if real Mollie data exists."""
    Payment = apps.get_model("payments", "Payment")
    mollie_rows = Payment.objects.filter(provider="mollie").count()
    if mollie_rows:
        raise RuntimeError(
            f"Cannot remove Mollie support: {mollie_rows} payment(s) with provider='mollie' exist. "
            "Export or migrate these records before applying this migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentwebhookevent_refundrequest'),
    ]

    operations = [
        migrations.RunPython(_ensure_no_mollie_payments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='payment',
            name='mollie_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mollie_payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('demo', 'Demo'), ('offline_pending', 'Offline Pending')], db_index=True, default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('demo', 'Demo'), ('offline_pending', 'Offline Pending')], db_index=True, max_length=20),
        ),
    ]
