# Generated by Django 6.0.6 on 2026-07-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_mollie_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ['-requested_at'], 'permissions': [('can_process_refunds', 'Can process refund requests against the payment provider')]},
        ),
    ]
