# Generated by Django 6.0.3 on 2026-04-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=100)),
                ('twilio_phone_number', models.CharField(blank=True, help_text='Twilio phone number to send from', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('send_order_confirmed', models.BooleanField(default=True)),
                ('send_order_ready', models.BooleanField(default=True)),
                ('send_order_delivered', models.BooleanField(default=False)),
                ('send_promotions', models.BooleanField(default=False)),
                ('max_daily_messages', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'SMS Settings',
                'verbose_name_plural': 'SMS Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_ready', 'Order Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Order Delivered'), ('promo', 'Promotional'), ('welcome', 'Welcome'), ('reminder', 'Reminder')], max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('twilio_sid', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
